### ISSUE TITLE
When I run the sh I ran into a problem

### ISSUE THREAD

**Issue by Hydraz320** [schinmayee/metric-learning#1]
Traceback as follows. Hoping to get some suggestions, thanks a lot!
![image](https://user-images.githubusercontent.com/11408874/34805731-9473c95c-f6ba-11e7-9601-0aff2c4c7332.png)

**Comment by Hydraz320** [comment]
Sorry, It's just because some mistake that I deleted one line code...Thanks anyway

**Comment by schinmayee** [comment]
Great. Thanks for letting me know!
